export default function Container() {
    return (
        <div className="container h-auto w-full frosted-glass-light dark:frosted-glass-dark">
            <h1 className="text-black dark:text-white font-source_code_pro text-6xl text-center">Title</h1>
            <p className="text-black dark:text-white font-quicksand text-lg text-center w-11/12 ml-auto mr-auto mt-6 mb-28">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet nulla facilisi morbi tempus. Sit amet nulla facilisi morbi tempus iaculis. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Integer eget aliquet nibh praesent tristique magna. Pellentesque elit eget gravida cum sociis. Sagittis aliquam malesuada bibendum arcu vitae elementum. Ornare massa eget egestas purus viverra accumsan in nisl nisi. Cursus metus aliquam eleifend mi in nulla. Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.
                Pellentesque habitant morbi tristique senectus et netus et malesuada. Nunc aliquet bibendum enim facilisis gravida neque. Ut venenatis tellus in metus vulputate eu scelerisque. Quam lacus suspendisse faucibus interdum posuere lorem. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Risus commodo viverra maecenas accumsan lacus. Phasellus egestas tellus rutrum tellus. Velit laoreet id donec ultrices tincidunt arcu. Convallis a cras semper auctor. Adipiscing at in tellus integer feugiat scelerisque varius. Donec enim diam vulputate ut pharetra sit amet aliquam. Porta nibh venenatis cras sed felis. Nunc mattis enim ut tellus elementum. Magnis dis parturient montes nascetur. Consequat interdum varius sit amet mattis vulputate enim nulla. Imperdiet dui accumsan sit amet nulla facilisi morbi.
                Adipiscing elit pellentesque habitant morbi tristique senectus et. Erat velit scelerisque in dictum non consectetur a. Sem et tortor consequat id porta nibh venenatis. Leo urna molestie at elementum eu facilisis sed odio. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies. Orci a scelerisque purus semper eget duis at tellus at. Et tortor consequat id porta nibh venenatis. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Viverra tellus in hac habitasse platea dictumst. Duis convallis convallis tellus id interdum velit laoreet id donec. Risus nec feugiat in fermentum posuere. Arcu non odio euismod lacinia at quis risus sed. Feugiat vivamus at augue eget arcu dictum varius duis. Purus faucibus ornare suspendisse sed nisi lacus. Pellentesque nec nam aliquam sem et tortor consequat id. Venenatis tellus in metus vulputate. Et leo duis ut diam quam nulla porttitor massa.
                Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Proin sed libero enim sed. Fermentum odio eu feugiat pretium nibh ipsum. Pellentesque elit ullamcorper dignissim cras tincidunt. Purus sit amet luctus venenatis lectus magna. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Urna id volutpat lacus laoreet non curabitur. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Sed libero enim sed faucibus turpis in eu. Cras fermentum odio eu feugiat. Aliquet porttitor lacus luctus accumsan tortor posuere. Feugiat in ante metus dictum at. Mi eget mauris pharetra et ultrices neque ornare aenean euismod.
                Tortor at auctor urna nunc id cursus metus. Vestibulum sed arcu non odio. Sapien pellentesque habitant morbi tristique senectus et netus et malesuada. Vitae congue eu consequat ac felis donec et. Faucibus purus in massa tempor. Sit amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Diam donec adipiscing tristique risus nec feugiat in fermentum. Cursus mattis molestie a iaculis at erat pellentesque. Quam quisque id diam vel quam elementum pulvinar etiam. Senectus et netus et malesuada fames ac. Purus sit amet luctus venenatis. Vitae auctor eu augue ut lectus arcu. Aliquam sem et tortor consequat id.
            </p>
        </div>
    )
}